services:
  - type: web
    name: kodolam-bot-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false #manually set on render dashboard
      - key: CHANNEL_ID
        sync: false
